### ISSUE TITLE
Is it possibile to add an option to pass a file and not a directory as an argument?

### ISSUE THREAD

**Issue by adellam** [openaire/Generic-Matomo-Tracker#7]
The script wants a directory, but it fails in my case because the directory is used by all the apache logs and the script fails. Also, I'm only interested to submit the logs of one of the virtualhosts (the others are test installations).

**Comment by dimitrispie** [comment]
> The script wants a directory, but it fails in my case because the directory is used by all the apache logs and the script fails. Also, I'm only interested to submit the logs of one of the virtualhosts (the others are test installations).

Fixed

**Comment by adellam** [comment]
Thanks, it works
